security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        users_in_memory:
            memory:
                users:
                    admin:
                        password: '$2y$13$AWSzI.kY2KONGPrQ/kdmDu7lfSG7A6bpaliekeHcyWr/k5Ldi1ACa'  # Mot de passe "admin"
                        roles: ['ROLE_ADMIN']

    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false

        main:
            lazy: true
            provider: users_in_memory
            form_login:
                login_path: login
                check_path: login
                default_target_path: accueil
            logout:
                path: logout
                target: login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
